CREATE TABLE [trx].[Accounts] (
    [BANK]            VARCHAR (255) NOT NULL,
    [ACCOUNT]         VARCHAR (255) NOT NULL,
    [ACCOUNT_TYPE_FK] VARCHAR (255) NOT NULL,
    [COMMENT]         VARCHAR (255) NULL,
    [FILENAME]        VARCHAR (255) NULL,
    [TEMPLATE]        VARCHAR (255) NOT NULL,
    CONSTRAINT [PK_Accounts] PRIMARY KEY CLUSTERED ([ACCOUNT] ASC),
    FOREIGN KEY ([ACCOUNT_TYPE_FK]) REFERENCES [trx].[Account_Types] ([ACCOUNT_TYPE]),
    CONSTRAINT [UC_FileName] UNIQUE NONCLUSTERED ([FILENAME] ASC)
);



