CREATE TABLE [trx].[Accounts] (
    [BANK]         VARCHAR (255) NOT NULL,
    [ACCOUNT]      VARCHAR (255) NOT NULL,
    [ACCOUNT_TYPE] VARCHAR (255) NOT NULL,
    [COMMENT]      VARCHAR (255) NULL,
    CONSTRAINT [PK_Accounts] PRIMARY KEY CLUSTERED ([ACCOUNT] ASC),
    FOREIGN KEY ([ACCOUNT_TYPE]) REFERENCES [trx].[Account_Types] ([ACCOUNT_TYPE])
);

